### ISSUE TITLE
Not using Argon2? (and other suggestions)

### ISSUE THREAD

**Issue by LoupVaillant** [MilesVII/spm_core#1]
Hi, I've just been referred to your password manager, thanks for having chosen my library!

I have noted a number of issues I wanted to share. Nothing critical, but one pretty serious. Now I understand that your password manager is deterministic, so changing anything will break backwards compatibility. I'd understand if you can't implement my suggestions because of that. Still, I thought I should share.

---

First, I don't see any mention of Argon2 in your code. Monocypher provides `crypto_argon2i()` specifically for hashing low entropy secrets such as passwords. Using Blake2b is a bit of a problem, because Blake2b is *fast*, and that allows offline guessing of your password. The attacker would only need 3 things:

- The salt (which may be public, and therefore ineffective, since you have a default salt).
- The string used to identify the targeted service (admittedly easily guessable, or even public).
- The generated password, which you do give to the service, and may be compromised.

If your salt is actually a *secret key*, no problem. But you must then treat it as such, and protect it effectively. If you expect attackers may get a hold of your salt (say they stole your configuration file), then the use of a fast hash is a problem.

My suggestion: use Argon2i, with 3 passes, with enough RAM for the computation to be tolerably long. Between 0.2 and 1.5 seconds, I'd say. in practice, this means a couple hundred megabytes.

---

Your compression is biased. What you likely want is take the hash in chunks of 4 bytes, interpret them all as a single number, *then* perform the modulo operation. Some bias will be left, but we don't care in this context. My suggestion: replace [this loop](https://github.com/MilesVII/spm_core/blob/master/toolkit.c#L56) by something like the following (I'm assuming 16 character passwords):

    	for (int i = 0; i < 64; i += 4){
    		int x = 0;
    		for (int j = 0; j < 4; ++j)
    			x += hash[i] << j; // parse little endian number
    		x %= strlen(charset);
    		password[i] = charset[x];
    	}

---

[The hash of the master password and target](https://github.com/MilesVII/spm_core/blob/master/toolkit.c#L50) are more complicated than they need to be. You can just combine them by using the incremental API of Blake2b:

    crypto_blake2b_ctx ctx;
    crypto_blake2b_init  (ctx);
    crypto_blake2b_update(ctx, master, strlen(master));
    crypto_blake2b_update(ctx, target, strlen(target));
    crypto_blake2b_final (ctx, hash);

That way, no need to combine intermediate keys. You can use that same trick to handle the salt instead of using `malloc(3)` and `strcpy(3)`:

    crypto_blake2b_ctx ctx;
    crypto_blake2b_init  (ctx);
    crypto_blake2b_update(ctx, salt  , strlen(salt  ));
    crypto_blake2b_update(ctx, master, strlen(master));
    crypto_blake2b_update(ctx, target, strlen(target));
    crypto_blake2b_final (ctx, hash);

That should simplify your code quite a bit. But that doesn't solve the problem of the slow hash, though. For this, you need Argon2i. I suggest you actually hash the password this way:

    crypto_argon2i_general(
        hash, 64,  // the size can be greater if you want
        work_area, // allocate a big enough one beforehand.
        200000,    // 200 MB (the more memory, the slower)
        3,         // 3 passes   (the more passes, the slower)
        master, strlen(master),
        salt  , strlen(salt),
        0, 0,      // no key
        target, strlen(target));

Maximum security in a single library call. :-)

---

Still, pretty good first attempt. Keep it up!  
Loup.

**Comment by MilesVII** [comment]
Thank you for all the attention paid to this project, I really appreciate it. I didn't know about more suitable hash function, so I will surely implement your suggestions as soon as I can

**Comment by MilesVII** [comment]
Well, better late than never. I changed hash function of main password generator to Argon2 as suggested, which works pretty slow on my laptop, so I guess it's fine. I also changed way how compression works, which I hope is ok too. 
And again, thanks!

**Comment by LoupVaillant** [comment]
OK, I took a look at your patch. Looks pretty good, except a very minor nitpick about the number of iterations in Argon2i (I prefer to stick to 3 iterations unless I don't have enough memory). Good to close as far as I can tell.
